### ISSUE TITLE
SOME/IP String Serialisation Limit 

### ISSUE THREAD

**Issue by sreethut** [FlorianMuenchbach/pysomeiptlv#1]
https://github.com/FlorianMuenchbach/pysomeiptlv/blob/51167372cd3c8a6b39d67dbedcbc92e1b6442c3e/someip/tlv/datatypes/complex/array_types.py#L197

Scenario:
path: Native SOME/IP Consumer to IPC SOME/IP Provider.

The consumer sent a SET Request on the resource (static and dynamic) with one element containing a big-sized string (attached as a JSON file) and results in Error: DataID must be in the range [0,0xFFF] or None.

**Comment by FlorianMuenchbach** [comment]
Hi @sreethut 

Thanks for reporting -- indeed, I did not assume strings larger than 4095 bytes will ever be used with this code.
I'll push a fix asap.

**Comment by FlorianMuenchbach** [comment]
Should be fixed now :)
@sreethut  please check if the fix resolves your issue

**Comment by sreethut** [comment]
Yes, this issue is fixed now :)
